name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - latexmk: 'yes'
            targets: ''
          - latexmk: ''
            targets: 'dvi'

    env:
      LATEXMK: ${{ matrix.latexmk }}
      TARGETS: ${{ matrix.targets }}

    steps:
      # Install texlive and other deps
    - name: Install deps
      run: |
        sudo apt-get install \
          wget \
          curl \
          sed \
          grep \
          texlive \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-latex-recommended \
          texlive-science-doc \
          texlive-science \
          texlive-metapost \
          texlive-xetex
  
    - name: Checkout repo
      uses: actions/checkout@v2
  
      # Install latexmk if needed
    - name: Install latexmk
      if: matrix.latexmk == 'yes'
      run: sudo apt-get install latexmk -y
          
    - name: Build
      run: make ${{ matrix.targets }}
