name: Update errata

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    # it seems impossible to update a branch in a forked repo with the default token
    if: ${{ ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch all tags for `git describe`
        run: git fetch --force --prune --unshallow --tags

      - name: Update ./errata.tex
        run: ./mark-errata

      - name: Push changes of ./errata.tex
        run: |
          if ! git diff --quiet -- ./errata.tex; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add errata.tex
            git commit -m "Mark Errata (auto)"
            git push
          fi
